import { NgModule } from '@angular/core';
import {
    MatButtonModule,
    MatIconModule,
    MatFormFieldModule,
    MatInputModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatCheckboxModule,
    MatSidenavModule,
    MatToolbarModule,
    MatListModule,
    MatTabsModule,
    MatCardModule,
    MatSelectModule,
    MatProgressSpinnerModule,
    MatDialogModule,
    MatTableModule,
    MatSnackBarModule,
    MatExpansionModule,
    MatTooltipModule,
    MatSlideToggleModule,
    MatSortModule,
    MatPaginatorModule
  } from '@angular/material';

@NgModule({
    imports: [
        MatInputModule,
        MatFormFieldModule, 
        MatButtonModule, 
        MatIconModule, 
        MatDatepickerModule,
        MatNativeDateModule,
        MatCheckboxModule,
        MatSidenavModule,
        MatToolbarModule,
        MatListModule,
        MatTabsModule,
        MatCardModule,
        MatSelectModule,
        MatProgressSpinnerModule,
        MatDialogModule,
        MatTableModule,
        MatSnackBarModule,
        MatExpansionModule,
        MatTooltipModule,
        MatSlideToggleModule,
        MatSortModule,
        MatPaginatorModule
    ],
    exports: [
        MatInputModule, 
        MatFormFieldModule, 
        MatButtonModule, 
        MatIconModule, 
        MatDatepickerModule,
        MatNativeDateModule,
        MatCheckboxModule,
        MatSidenavModule,
        MatToolbarModule,
        MatListModule,
        MatTabsModule,
        MatCardModule,
        MatSelectModule,
        MatProgressSpinnerModule,
        MatDialogModule,
        MatTableModule,
        MatSnackBarModule,
        MatExpansionModule,
        MatTooltipModule,
        MatSlideToggleModule,
        MatSortModule,
        MatPaginatorModule
    ]
})

export class MaterialModule{}